# Generated by Django 4.1.13 on 2024-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=150, unique=True)),
                ('User_Email', models.EmailField(max_length=254, unique=True)),
                ('User_Password', models.CharField(max_length=128)),
            ],
        ),
    ]
