# Generated by Django 4.1.13 on 2024-10-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Register_Data',
        ),
    ]
